### ISSUE TITLE
Multi-module error

### ISSUE THREAD

**Issue by joaodevsantos** [alaegin/Detekt-Action#70]
I have a multi-module project where we are using detekt for some modules but not for all. When tried to push changes the plugin gave check-warnings but since we treat them as errors it fails the CI/CD. I'm planning to change in the meanwhile to use the gradle detekt task to not block the team/project pace but was this considered on your plugin?

**Comment by alaegin** [comment]
Hello!

I've never tried to disable detekt checks in modules. We always check all the modules we own.

**Comment by joaodevsantos** [comment]
Would this be a nice feature to have? At least when you have a legacy project or modules on a different state it would be interesting to apply only detekt on those

**Comment by joaodevsantos** [comment]
I will try to use the flag `detekt_excludes` but it would be interesting one day to understand in which modules detekt is being applied to run the action only on those

**Comment by alaegin** [comment]
It would be difficult to implement because the current implementation knows nothing about the Gradle and modules. It just runs from the project's root folder and scans everything except excluded files.

I suggest you to use gradle detekt plugin as you mentioned before or `detekt_excludes` to exclude specific folders.

**Comment by joaodevsantos** [comment]
Appreciate, thanks for the feedback will do it! 🚀
